- name: Sublime
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Add Sublime APT package key
      become: yes
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
      when: not is_mac

    - name: Add Sublime APT package repository
      become: yes
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        filename: sublime
        update_cache: no
      register: apt_repository
      when: not is_mac

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Sublime tools (desktop Linux)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - sublime-merge
        - sublime-text
      when: not is_mac and not is_wsl

    - name: Install Sublime tools (WSL 2)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - sublime-merge
      when: not is_mac and is_wsl

    # macOS

    - name: Install Sublime tools (macOS)
      homebrew_cask:
        name: "{{ item }}"
      loop:
        - sublime-merge
        - sublime-text
      when: is_mac
