- import_playbook: ../rust-lang/core.yaml    # Need cargo to install Alacritty

- name: Alacritty
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[Non-WSL] Install pre-requisites"
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Alacritty (Linux)
      become: yes
      apt:
        package: alacritty
      when: is_ubuntu and not is_wsl

    - name: Check if gnome-terminal exists
      stat:
        path: /usr/bin/gnome-terminal.wrapper
      register: gt_file_info
      when: is_ubuntu

    - name: Set gnome terminal as Default
      become: yes
      alternatives:
        name: x-terminal-emulator
        path: "/usr/bin/gnome-terminal.wrapper"
        priority: 49
      when: is_ubuntu and gt_file_info.stat.exists

    # macOS

    - name: Install Alacritty (macOS)
      homebrew_cask:
        name: alacritty
      when: is_mac
