- name: Docker
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Add Docker APT package key
      become: yes
      get_url:
        url: https://download.docker.com/linux/{{ distribution | lower }}/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

    - name: Add Docker APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=arm64, signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ distribution | lower }} {{ ansible_distribution_release }} stable
        filename: docker
        update_cache: no
      register: apt_repository_docker

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository_docker.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Docker engine
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli

    - name: Enable Docker engine for current user
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes

    - name: "Install sysbox-ce"
      become: yes
      apt:
        deb: https://downloads.nestybox.com/sysbox/releases/v0.6.2/sysbox-ce_0.6.2-0.linux_arm64.deb
      when: not is_wsl

    # - name: Determine Docker Machine latest version
    #   shell:
    #     cmd: "curl -s https://api.github.com/repos/docker/machine/releases/latest | grep \"browser_download_url.*Linux-aarch64\\\"\" | cut -d : -f 2,3 | tr -d \\\""
    #     warn: false
    #   register: docker_machine_version

    # - name: Install Docker Machine
    #   become: yes
    #   get_url:
    #     url: "{{ docker_machine_version.stdout }}"
    #     dest: /usr/local/bin/docker-machine
    #     mode: 0755
