- name: QEMU/KVM
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') | lower is search('microsoft') }}

    - name: Install QEMU/KVM
      become: yes
      apt:
        package:
          - bridge-utils
          - libvirt-clients
          - libvirt-daemon-system
          - ovmf
          - qemu-kvm
          - virt-manager
      when: not is_wsl

    - name: Enable QEMU/KVM for current user
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=libvirt
        append=yes
      when: not is_wsl
